const refs = {
  loaderPartOne: document.querySelectorAll('.bars-common'),
  loaderPartTwo: document.querySelectorAll('.squares-common'),
  errorNotification: document.querySelector('.main__error-notification'),
  main: document.querySelector('.main'),
  detailsSection: document.querySelector('.details-page'),
  libraryFilrt: document.querySelector('.library-filter'),
  paginationWrapper: document.querySelector('.pagination'),
  ulForCards: document.querySelector('.gallery__list'),
  reviewCard: document.querySelector('.review'),
  sliderContainer: document.querySelector('.my-slider'),
  body: document.querySelector('.body'),

  btnTop: document.querySelector('.main__btn-scroll'),
  modalBtn: document.querySelector('.backdrop__modal__btn'),
  backdrop: document.querySelector('.backdrop'),
  player: document.querySelector('#player'),

  form: document.querySelector('.main__search-form'),
  input: document.getElementById('search-form'),
  searchByMovie: document.getElementById('option-movie'),
  searchByActor: document.getElementById('option-actor'),
  selectedOption: document.getElementsByClassName('selected-option'),
  clearInputBtn: document.querySelector('.search-form__clear'),

  btnMyLibrary: document.querySelector('.library'),
  btnHome: document.querySelector('[data-home]'),

  filmsLibrary: document.querySelector('.js-gallery'),
  btnWatched: document.querySelector('.btnWatched'),
  btnQueue: document.querySelector('.btnQueue'),

  thrillerRef: document.querySelector('[data-thriller]'),
  comedyRef: document.querySelector('[data-comedy]'),
  animationRef: document.querySelector('[data-animation]'),
  actionRef: document.querySelector('[data-action]'),
  westernRef: document.querySelector('[data-western]'),
  fantasyRef: document.querySelector('[data-fantasy]'),
  dramaRef: document.querySelector('[data-drama]'),

  logoText: document.querySelector('[data-logoText]'),

  homePage: document.querySelector('[data-home]'),
  libraryPage: document.querySelector('[data-library]'),

  layer: document.querySelector('.layer__bg'),
  title: document.querySelector('.parallax-logo'),
  title2: document.querySelectorAll('.parallax-item'),
  decor1: document.querySelector('.decoration-first'),
  decor2: document.querySelector('.decoration-second'),

  iconButton: document.querySelector('[data-icon]'),

  welcomeTextSignIn: document.querySelector('.auth__title.sign-in'),
  welcomeTextSignUp: document.querySelector('.auth__title.sign-up'),
};

const {
  loaderPartOne,
  loaderPartTwo,
  errorNotification,
  main,
  detailsSection,
  libraryFilrt,
  paginationWrapper,
  ulForCards,
  btnTop,
  modalBtn,
  backdrop,
  player,
  form,
  btnMyLibrary,
  filmsLibrary,
  btnWatched,
  btnQueue,
  thrillerRef,
  comedyRef,
  actionRef,
  animationRef,
  westernRef,
  fantasyRef,
  dramaRef,
  logoText,
  homePage,
  libraryPage,
  layer,
  title,
  title2,
  decor1,
  decor2,
  iconButton,

  reviews,
  searchByMovie,
  searchByActor,
  selectedOption,
  input,
  clearInputBtn,

  reviewCard,
  sliderContainer,

  welcomeTextSignIn,
  welcomeTextSignUp,
  btnHome,
  body,
} = refs;
